package com.document.sensitive.mask.app.constants;

import java.util.Arrays;
import java.util.List;

public interface ApplicationConstants {
	public static final String DOCUMENT_AI_PROCESSORS_LOCATION = "us";
	public static final String PROJECT_ID = "videoanalyzer-455321";
	public static final String PROCESSOR_ID = "501dfab435adaaeb";

	public static final List<String> infoTypes = Arrays.asList(
			// Core PII (Globally Supported)
			"PERSON_NAME", "EMAIL_ADDRESS", "PHONE_NUMBER", "DATE_OF_BIRTH", "STREET_ADDRESS", "PASSPORT",
			// Universal Financial/Document Identifiers (Using general detectors)
			"CREDIT_CARD_NUMBER", "IBAN_CODE", // International Bank Account Standard
			"FINANCIAL_ACCOUNT_NUMBER", // ✅ The robust generic detector for bank/account numbers
			"GOVERNMENT_ID", // ✅ Detector for generic Government IDs (covers many DL formats)

			// Highly Specific Country IDs (These are usually fine)
			"US_SOCIAL_SECURITY_NUMBER");

	public static final List<String> globalInfoTypes = Arrays.asList(
			// FINANCIAL & BANKING (22)
			"FINANCIAL_ACCOUNT_NUMBER", "CREDIT_CARD_NUMBER", "IBAN_CODE", "SWIFT_CODE", "US_BANK_ROUTING_MICR",
			"CANADA_BANK_ACCOUNT", "JAPAN_BANK_ACCOUNT", "PORTUGAL_NIB_NUMBER", "US_EMPLOYER_IDENTIFICATION_NUMBER",
			"US_INDIVIDUAL_TAXPAYER_IDENTIFICATION_NUMBER", "AUSTRALIA_TAX_FILE_NUMBER", "UK_TAXPAYER_REFERENCE",
			"VAT_NUMBER", "FINANCIAL_ID", "CREDIT_CARD_EXPIRATION_DATE", "CREDIT_CARD_TRACK_NUMBER", "CVV_NUMBER",
			"AMERICAN_BANKERS_CUSIP_ID", "SPAIN_CIF_NUMBER", "US_ADOPTION_TAXPAYER_IDENTIFICATION_NUMBER",
			"PORTUGAL_NIB_NUMBER", "CANADA_OHIP",

			// PII CORE & LOCATION (10)
			"PERSON_NAME", "FIRST_NAME", "LAST_NAME", "EMAIL_ADDRESS", "PHONE_NUMBER", "DATE_OF_BIRTH",
			"STREET_ADDRESS", "LOCATION", "LOCATION_COORDINATES", "AGE",

			// GOVERNMENT IDs & PASSPORTS (30)
			"GOVERNMENT_ID", "PASSPORT", "US_PASSPORT", "US_SOCIAL_SECURITY_NUMBER", "US_DRIVERS_LICENSE_NUMBER",
			"CANADA_SOCIAL_INSURANCE_NUMBER", "CANADA_DRIVERS_LICENSE_NUMBER", "UK_NATIONAL_INSURANCE_NUMBER",
			"UK_DRIVERS_LICENSE_NUMBER", "IRELAND_PPSN", "CHINA_RESIDENT_ID_NUMBER", "INDIA_AADHAAR_INDIVIDUAL",
			"INDIA_PAN_INDIVIDUAL", "BRAZIL_CPF_NUMBER", "GERMANY_IDENTITY_CARD_NUMBER", "MEXICO_CURP_NUMBER",
			"NETHERLANDS_BSN_NUMBER", "FRANCE_CNI", "FRANCE_NIR", "SPAIN_DNI_NUMBER", "JAPAN_INDIVIDUAL_NUMBER",
			"AUSTRALIA_DRIVERS_LICENSE_NUMBER", "AUSTRALIA_MEDICARE_NUMBER", "POLAND_PESEL_NUMBER",
			"THAILAND_NATIONAL_ID_NUMBER", "UK_NATIONAL_HEALTH_SERVICE_NUMBER", "IRELAND_EIRCODE",
			"UK_ELECTORAL_ROLL_NUMBER", "GENDER", "DRIVERS_LICENSE_NUMBER",

			// SECURITY & TECHNICAL (13)
			"GCP_API_KEY", "GCP_CREDENTIALS", "AWS_CREDENTIALS", "AUTH_TOKEN", "OAUTH_CLIENT_SECRET", "JSON_WEB_TOKEN",
			"PASSWORD", "ENCRYPTION_KEY", "IP_ADDRESS", "MAC_ADDRESS", "BASIC_AUTH_HEADER", "XSRF_TOKEN", "URL"

	);
}
